### ISSUE TITLE
Remove unnecessary dependencies

### ISSUE THREAD

**Issue by bdominguez** [mxjones/RedBus#8]
I want to use your library (.NET Standard 2.0) but it adds some dependencies that are not necessary and I don't want them in my project.

https://github.com/mxjones/RedBus/blob/master/src/Redbus/Redbus/Redbus.csproj

You can remove this block and it will compile fine.

```xml
  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.Reflection.Emit.LightWeight" Version="4.3.0" />
    <PackageReference Include="System.Dynamic.Runtime" Version="4.3.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net45' ">
    <Reference Include="System" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Core" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
```

**Comment by mxjones** [comment]
Hi,

Ah right - thanks for this, didn't realise this wasn't required...I will take a look into this and remove those if they are not required!

Cheers!

**Comment by mxjones** [comment]
Removed these in 1.0.7
